# Generated by Django 4.0.1 on 2022-01-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='isVisible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='done_date',
            field=models.DateTimeField(blank=True, default=None, verbose_name='date done'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
