# Generated by Django 4.0.1 on 2022-01-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_isvisible_alter_todo_done_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='done_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date done'),
        ),
    ]
