# Generated by Django 4.0.1 on 2022-01-20 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='isVisible',
        ),
    ]
